/**
 * Cynos Database - TypeScript Type Definitions
 *
 * This module provides TypeScript types and wrappers for the Cynos WASM database.
 */

// Re-export WASM types (will be generated by wasm-pack)
export type { Database, JsTableBuilder, JsTable, SelectBuilder, InsertBuilder, UpdateBuilder, DeleteBuilder, JsTransaction, JsObservableQuery, JsChangesStream, Column, Expr } from './wasm';

/** Data types supported by Cynos */
export type DataType =
  | 'boolean'
  | 'int32'
  | 'int64'
  | 'float64'
  | 'string'
  | 'bytes'
  | 'datetime'
  | 'jsonb';

/** Sort order for ORDER BY clauses */
export type SortOrder = 'asc' | 'desc';

/** Column options for table creation */
export interface ColumnOptions {
  primaryKey?: boolean;
  nullable?: boolean;
  unique?: boolean;
  autoIncrement?: boolean;
}

/** Change set from observable queries */
export interface ChangeSet<T = Record<string, unknown>> {
  added: T[];
  removed: T[];
  modified: Array<{ old: T; new: T }>;
}

/** Query result row type */
export type Row = Record<string, unknown>;

/** Subscription callback type */
export type SubscriptionCallback<T = ChangeSet> = (changes: T) => void;

/** Unsubscribe function type */
export type Unsubscribe = () => void;
